<center> <font color = #82318E size = 5 face = "微软雅黑" > RBF Tensor Version の Damon </font> </center>

In [1]:
import numpy as np

<center> <font color = #82318E size = 4 face = "微软雅黑" > 1. Prepare Data </font> </center>

In [2]:
np.random.seed(522)

im = 9

temp = np.random.normal(loc = 0, scale = 1, size = (im, 13))

H = temp[::, 0:3:1]
Tx = temp[::, 4:7:1]
Ty = temp[::, 7:10:1]
Tz = temp[::, -3::1]

print(' The shape of H  is {};\n The shape of Tx is {};\n The shape of Ty is {};\n The shape of Tz is {}.'.format(
      H.shape,Tx.shape,Ty.shape,Tz.shape))

 The shape of H  is (9, 3);
 The shape of Tx is (9, 3);
 The shape of Ty is (9, 3);
 The shape of Tz is (9, 3).


<center> <font color = #82318E size = 4 face = "微软雅黑" > 2. Original Version </font> </center>

<table border = '0' witdth = '2000' >
<tr> 
<td width = '2000' ><img src = ./TensorOrig.png /></td> 
</tr>
</table>

In [3]:
p = np.multiply(H[:,0], Tx[:,0]) + np.multiply(H[:,1], Ty[:,0]) + np.multiply(H[:,2], Tz[:,0])
q = np.multiply(H[:,0], Tx[:,1]) + np.multiply(H[:,1], Ty[:,1]) + np.multiply(H[:,2], Tz[:,1])
s = np.multiply(H[:,0], Tx[:,2]) + np.multiply(H[:,1], Ty[:,2]) + np.multiply(H[:,2], Tz[:,2])
print(p.shape, q.shape, s.shape)
print()

AIM = np.concatenate((p.reshape(-1, 1), q.reshape(-1, 1), s.reshape(-1, 1)), axis = 1)
print(AIM.shape)
print(AIM)

(9,) (9,) (9,)

(9, 3)
[[-0.4702549  -1.09373498  0.71895093]
 [-4.34420159  1.93786275  1.27702953]
 [-0.79210234 -0.6952026  -0.78218299]
 [ 1.90391861 -1.60849709 -2.27491605]
 [ 4.405149    0.28022822 -1.9293554 ]
 [ 1.17188343 -1.65311901 -0.04564163]
 [-1.65806898 -0.72016552 -0.64827817]
 [ 2.80186909  0.9698682  -0.11173106]
 [-3.2307313  -2.67230977 -1.38377616]]


<center> <font color = #82318E size = 4 face = "微软雅黑" > 3. Tensor Slice(Matrix) Version </font> </center>

<table border = '0' witdth = '2000' >
<tr> 
<td width = '2000' ><img src = ./TensorSlice.jpeg /></td> 
</tr>
</table>

In [4]:
T = np.concatenate((Tx, Ty, Tz), axis = 0).reshape(-1, im, 3)
print(T.shape)

(3, 9, 3)


In [5]:
p_prime = np.dot(np.multiply(np.eye(im, im), np.dot(H, T[::, ::, 0])), np.ones((im, 1)))
q_prime = np.dot(np.multiply(np.eye(im, im), np.dot(H, T[::, ::, 1])), np.ones((im, 1)))
s_prime = np.dot(np.multiply(np.eye(im, im), np.dot(H, T[::, ::, 2])), np.ones((im, 1)))
print(np.concatenate((p_prime, q_prime, s_prime), axis = 1))

[[-0.4702549  -1.09373498  0.71895093]
 [-4.34420159  1.93786275  1.27702953]
 [-0.79210234 -0.6952026  -0.78218299]
 [ 1.90391861 -1.60849709 -2.27491605]
 [ 4.405149    0.28022822 -1.9293554 ]
 [ 1.17188343 -1.65311901 -0.04564163]
 [-1.65806898 -0.72016552 -0.64827817]
 [ 2.80186909  0.9698682  -0.11173106]
 [-3.2307313  -2.67230977 -1.38377616]]


<center> <font color = #82318E size = 4 face = "微软雅黑" > 4. Tensor Version </font> </center>

<center> <font color = #82318E size = 3 face = "微软雅黑" > 4.1 Tensor Version (Numpy) </font> </center>

<table border = '0' witdth = '2000' >
<tr> 
<td width = '2000' ><img src = ./Tensor.jpeg /></td> 
</tr>
</table>

In [7]:
'''
is the same as 
T = np.concatenate((Tx, Ty, Tz), axis = 0).reshape(-1, im, 3)
'''
T = np.stack((Tx, Ty, Tz), axis = 0)
One_tensor = np.stack((np.eye(im, im), np.eye(im, im), np.eye(im, im)), axis = 2)
print(H.shape, T.shape, One_tensor.shape)

(9, 3) (3, 9, 3) (9, 9, 3)


In [7]:
print(np.sum(np.multiply(np.tensordot(H, T, axes = (1, 0)), One_tensor), axis = 0))

[[-0.4702549  -1.09373498  0.71895093]
 [-4.34420159  1.93786275  1.27702953]
 [-0.79210234 -0.6952026  -0.78218299]
 [ 1.90391861 -1.60849709 -2.27491605]
 [ 4.405149    0.28022822 -1.9293554 ]
 [ 1.17188343 -1.65311901 -0.04564163]
 [-1.65806898 -0.72016552 -0.64827817]
 [ 2.80186909  0.9698682  -0.11173106]
 [-3.2307313  -2.67230977 -1.38377616]]


In [31]:
print(np.tensordot(H, T, axes = (1, 0)))

[[[-0.4702549  -1.09373498  0.71895093]
  [ 0.97867456 -0.3994557  -0.19627198]
  [ 0.35778565 -0.16557194  0.46220189]
  [-0.45552777  0.63640789  0.6551166 ]
  [-1.06336823  0.25334637  0.2145882 ]
  [-0.27659288  1.13330329 -0.32825987]
  [-0.17882614 -0.73266177  0.68569048]
  [ 1.07010198  0.43203027  0.65165838]
  [-0.74866471 -0.428114   -0.09345973]]

 [[ 2.54242099  4.79159947 -3.61450688]
  [-4.34420159  1.93786275  1.27702953]
  [-2.10795961  0.38519769 -2.55775196]
  [ 1.68175742 -2.72262405 -3.82977733]
  [ 4.13311308 -1.17678882 -0.41013847]
  [ 2.08003927 -5.96476726  1.80664798]
  [ 1.41386115  3.79582884 -3.23415625]
  [-5.71390716 -2.31683205 -3.54411025]
  [ 3.54174696  2.46640241  0.76245229]]

 [[ 0.1635514  -0.06548322 -0.52437128]
  [ 0.76858049 -0.14951629  0.80793396]
  [-0.79210234 -0.6952026  -0.78218299]
  [-0.21752564  0.89357359 -1.21449271]
  [-1.24439705  0.26308134  1.12157733]
  [ 1.1048893  -1.09185902 -0.24201179]
  [ 1.03732423  0.83603994 -0.167288

<center> <font color = #82318E size = 3 face = "微软雅黑" > 4.2 Tensor Version (Tensorflow) </font> </center>

In [8]:
import tensorflow as tf

In [9]:
with tf.name_scope('H'):
    Tensor_1 = tf.placeholder(dtype = tf.float64, shape = (None, 3), name = 'H')
    tf.summary.histogram('H', Tensor_1)
    
with tf.name_scope('T'):
    Tensor_2 = tf.placeholder(dtype = tf.float64, shape = (9, 3), name = 'Tx')
    Tensor_3 = tf.placeholder(dtype = tf.float64, shape = (9, 3), name = 'Ty')
    Tensor_4 = tf.placeholder(dtype = tf.float64, shape = (9, 3), name = 'Tz')
    tf.summary.histogram('Tx', Tensor_2)
    tf.summary.histogram('Ty', Tensor_3)
    tf.summary.histogram('Tz', Tensor_4)
    
with tf.name_scope('fetch'):
    Tensor_5 = tf.placeholder(dtype = tf.float64, shape = (9, 9, 3), name = 'One')
    tf.summary.histogram('fetch', Tensor_5)

Tensor_6 = tf.stack((Tensor_2, Tensor_3, Tensor_4), axis = 0)
Tensor_7 = tf.reduce_sum(tf.multiply(tf.tensordot(Tensor_1, Tensor_6, axes = ([1], [0])), Tensor_5), axis = 0)
tf.summary.histogram('Result', Tensor_7)

with tf.Session() as sess:
    
    merged = tf.summary.merge_all()
    writer = tf.summary.FileWriter('./log', sess.graph)
    
    print(sess.run(Tensor_7, 
                   feed_dict = {Tensor_1: H, Tensor_2: Tx, Tensor_3: Ty, Tensor_4: Tz, Tensor_5: One_tensor}))

[[-0.4702549  -1.09373498  0.71895093]
 [-4.34420159  1.93786275  1.27702953]
 [-0.79210234 -0.6952026  -0.78218299]
 [ 1.90391861 -1.60849709 -2.27491605]
 [ 4.405149    0.28022822 -1.9293554 ]
 [ 1.17188343 -1.65311901 -0.04564163]
 [-1.65806898 -0.72016552 -0.64827817]
 [ 2.80186909  0.9698682  -0.11173106]
 [-3.2307313  -2.67230977 -1.38377616]]


<table border = '0' witdth = '2000' >
<tr> 
<td width = '2000' ><img src = ./graph.png /></td> 
</tr>
</table>

In [10]:
!tensorboard --logdir=./log

Starting TensorBoard b'47' at http://0.0.0.0:6006
(Press CTRL+C to quit)
^C
